import random
from typing import List, Optional, Type

from donjuan.cell import Cell, SquareCell
from donjuan.dungeon import Dungeon
from donjuan.grid import Grid
from donjuan.room import Room


class Randomizer:
    """
    Class for randomizing features of a dungeon.
    """

    def randomize_cell(self, cell: Cell) -> None:
        """Randomize properties of the `Cell`"""
        pass  # pragma: no cover

    def randomize_dungeon(self, dungeon: Dungeon) -> None:
        """Randomize properties of the `Dungeon`"""
        pass  # pragma: no cover

    def randomize_grid(self, grid: Grid) -> None:
        """Randomize properties of the `Grid`"""
        pass  # pragma: no cover

    def randomize_room(self, room: Room) -> None:
        """Randomize properties of the `Room`"""
        pass  # pragma: no cover

    @classmethod
    def seed(cls, seed: Optional[int] = None) -> None:
        """
        Args:
            seed (Optional[int]): seed passed to :meth:`random.seed`
        """
        random.seed(seed)


class RandomFilled(Randomizer):
    """
    Randomly set the :attr:`filled` attribute of cells.
    """

    def randomize_cell(self, cell: Cell) -> None:
        """Randomly fill the cell with probability 50%"""
        cell.filled = bool(random.randint(0, 1))

    def randomize_grid(self, grid: Grid) -> None:
        """Randomly fill all cells of the grid individually"""
        for i in range(grid.n_rows):
            for j in range(grid.n_cols):
                self.randomize_cell(grid.cells[i][j])
        return


class RoomRandomizer(Randomizer):
    """
    Randomize the features of a `Room`.
    """

    def __init__(
        self, min_size: int = 3, max_size: int = 9, cell_type: Type[Cell] = SquareCell
    ):
        assert issubclass(cell_type, Cell)
        assert min_size >= 1
        assert max_size >= min_size
        assert max_size <= 100  # arbitrary
        self.min_size = 2
        self.max_size = 4
        self.cell_type = cell_type

    def randomize_room(self, room: Room) -> None:
        """
        Randomly determine the size of the room, and set the cells of
        the room to a 2D array of unfilled cells of that size.
        """
        # Draw the dimensions
        height = random.randint(self.min_size, self.max_size)
        width = random.randint(self.min_size, self.max_size)

        # Create empty cells and set them in the room
        cells = [
            [self.cell_type(filled=False, coordinates=(i, j)) for j in range(height)]
            for i in range(width)
        ]
        room.set_cells(cells)
        return


def DungeonRoomRandomizer(Randomizer):
    """
    Randomize a dungeon by first creating rooms and then applying
    :meth:`RoomRandomizer.room_randomize` to them.

    Args:
        room_randomizers (Optional[List[RoomRandomizer]]): randomizers to
            to apply to each room generated by this randomizer
    """

    def __init__(
        self,
        room_randomizers: Optional[List[RoomRandomizer]] = None,
        max_room_attempts: int = 100,
    ):
        self.room_randomizers = room_randomizers or [RoomRandomizer()]
        for room_randomizer in self.room_randomizers:
            assert isinstance(room_randomizer, RoomRandomizer)
        self.max_room_attempts = max_room_attempts

    def get_number_of_rooms(self, grid_n_rows: int, grid_n_cols: int) -> int:
        """
        Randomly determine the number of rooms based on the size
        of the in coming grid.

        Args:
            grid_n_rows (int): number of rows
            grid_n_cols (int): number of columns
        """
        grid_area = grid_n_rows * grid_n_cols
        max_room_area = self.room_randomizer.max_size ** 2
        return grid_area // max_room_area

    def randomize_dungeon(self, dungeon: Dungeon) -> None:
        """
        Randomly put rooms in the dungeon.

        .. todo:: Make a `Labeler` object.

        .. todo:: Offload the room shift logic to a different randomizer.
        """
        # Compute then umber
        n_rooms = self.get_number_of_rooms(dungeon.grid.n_rows, dungeon.grid.n_cols)

        # Create rooms, randomize, and check for
        i = 0
        label = 0
        while len(dungeon.rooms) < n_rooms:
            # Create the room and randomize
            room = Room(name=label)
            for room_randomizer in self.room_randomizers:
                room_randomizer.randomize_room(room)

            # Draw random positions and shift
            room.shift_horizontal(random.randint(0, dungeon.n_cols - room.n_cols))
            room.shift_vertical(random.randint(0, dungeon.n_rows - room.n_rows))

            overlaps = False
            for existing_room in dungeon.rooms:
                if room.overlaps(existing_room):
                    overlaps = True
                    break

            if not overlaps:
                dungeon.add_room(room)
                label += 1

            # Check for max attempts
            i += 1
            if i == self.max_room_attempts:
                break
        return
